### PR TITLE
[maint] Pydantic v2 compatibility

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
This PR cribs what Grzegorz did in napari:
https://github.com/napari/napari/pull/6358/files#diff-294a92f946dab363f9541653745418fadd87a0f6e98f1dd201d6725325776cf9

It uses pydantic.v1 as a compatibility namespace.

I had strange issues with tests locally, see issue, but I think that's not related to this PR.

### CODE REVIEW

**Comment by kevinyamauchi** [comment]
Thanks for the PR, @psobolewskiPhD ! You're on fire. I don't have time to have a look over the weekend, but will do so next week. Please don't hesitate to ping me on zulip if I forget to come back. Thanks again!

**Comment by psobolewskiPhD** [comment]
Gah, these errors look to be pydantic v2 being imported--note the deprecation warning when we should be using v1 namespace. The second error appears to be due to double import from pydantic.v1 and pydantic.
I think it's from psygnal, because both errors are from a file (morphosamplers/spline.py) that imports from `psygnal`:
https://github.com/morphometrics/morphosamplers/blob/82fe35c88c33edad55c2ec5cd4c591f89bd73c9e/src/morphosamplers/spline.py#L7

And `psygnal` imports pydantic and uses pydantic.BaseModel:
https://github.com/pyapp-kit/psygnal/blob/15d95683b45964938d6713e6df6fc526c3792c88/src/psygnal/_evented_model.py

**Comment by psobolewskiPhD** [comment]
I'll try using https://github.com/pyapp-kit/pydantic-compat instead?

**Comment by kevinyamauchi** [comment]
I had a quick look at the error and the first error looks like it's because we're using the pydantic `Config` class instead of the `ConfigDict`. I think the second is that we somehow have a validator duplicated. I can make a PR to your branch and see if that fixes it.

**Comment by kevinyamauchi** [comment]
I made a small PR that I _think_ will fix the issue with the valiator: https://github.com/psobolewskiPhD/morphosamplers/pull/1

I didn't have time to do the config dict compatibility, but looking at the readme, it looks like  https://github.com/pyapp-kit/pydantic-compat has a solution for that

**Comment by psobolewskiPhD** [comment]
Yeah, I've got something working with pydantic-compat. I'll look at your PR though!

**Comment by psobolewskiPhD** [comment]
@kevinyamauchi I think we should close this in favor of https://github.com/morphometrics/morphosamplers/pull/35

**Comment by kevinyamauchi** [comment]
> @kevinyamauchi I think we should close this in favor of https://github.com/morphometrics/morphosamplers/pull/35

works for me!

**Pull request closed without merging**
